version: '1.0'

services:
    rabbit-mq:
        hostname: rabbit
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        ports:
            - "5672:5672"

    celery-worker:
        build:
          context: .
          dockerfile: dockerfile
        image: &worker bstiel/docker-healthcheck:0.1
        restart: always
        command: celery --app=worker.app worker
        environment: &environment
          - "CELERY_BROKER_URL=redis://celery-broker:6379/1"
          - "CELERY_WORKER_CONCURRENCY=1"
        healthcheck:
          test: ["CMD-SHELL", "celery inspect ping --destination celery@$$HOSTNAME"]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 5s
        volumes:
          - ./:/app

    celery-producer:
        image: *worker
        command: python producer.py
        environment: *environment
        healthcheck:
          test: ["NONE"]
        volumes:
          - ./:/app
